In [112]:
import pandas as pd
from datetime import date
import numpy as np

df = pd.read_csv("data/raw/Sample - Superstore.csv", encoding="cp1252", dtype={"Postal Code": "str"}, index_col=0)
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%m/%d/%Y").dt.normalize()
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%m/%d/%Y").dt.normalize()

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 1 to 9994
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   str
 1   Order Date     9994 non-null   datetime64[us]
 2   Ship Date      9994 non-null   datetime64[us]
 3   Ship Mode      9994 non-null   str
 4   Customer ID    9994 non-null   str
 5   Customer Name  9994 non-null   str
 6   Segment        9994 non-null   str
 7   Country        9994 non-null   str
 8   City           9994 non-null   str
 9   State          9994 non-null   str
 10  Postal Code    9994 non-null   str
 11  Region         9994 non-null   str
 12  Product ID     9994 non-null   str
 13  Category       9994 non-null   str
 14  Sub-Category   9994 non-null   str
 15  Product Name   9994 non-null   str
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(1), str(14)
memory usage: 1.5 MB

In [24]:
df.shape

(9994, 20)

In [25]:
df.describe()

,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
mean,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,229.858001,3.789574,0.156203,28.656896
min,2014-01-03 00:00:00,2014-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2015-05-23 00:00:00,2015-05-27 00:00:00,17.280000,2.000000,0.000000,1.728750
50%,2016-06-26 00:00:00,2016-06-29 00:00:00,54.490000,3.000000,0.200000,8.666500
75%,2017-05-14 00:00:00,2017-05-18 00:00:00,209.940000,5.000000,0.200000,29.364000
max,2017-12-30 00:00:00,2018-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,NaN,NaN,623.245101,2.225110,0.206452,234.260108

In [22]:
df.isna().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [48]:
df.head(3)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [63]:
df["Ship Mode"].value_counts()
df[df["Ship Mode"] == "Same Day"].describe()

,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,543,543,543.000000,543.000000,543.000000,543.000000
mean,2016-06-07 18:04:38.453038,2016-06-07 19:08:17.237569,236.396179,3.609576,0.152394,29.266591
min,2014-02-18 00:00:00,2014-02-18 00:00:00,0.556000,1.000000,0.000000,-3839.990400
25%,2015-09-15 00:00:00,2015-09-15 00:00:00,16.615000,2.000000,0.000000,2.156700
50%,2016-07-04 00:00:00,2016-07-04 00:00:00,55.176000,3.000000,0.200000,8.027000
75%,2017-06-07 00:00:00,2017-06-07 00:00:00,209.793000,5.000000,0.200000,29.563500
max,2017-12-27 00:00:00,2017-12-27 00:00:00,7999.980000,14.000000,0.800000,2229.024000
std,NaN,NaN,555.258791,2.129233,0.198365,226.689497

In [ ]:
#df["Date Diff"] = np.busday_count(df["Order Date"].values.astype("datetime64[D]"), df["Ship Date"].values.astype("datetime64[D]"))
df.insert(3, "Date Diff", np.busday_count(df["Order Date"].values.astype("datetime64[D]"), df["Ship Date"].values.astype("datetime64[D]")))
df[df["Ship Mode"] == "Standard Class"].describe()

,Order Date,Ship Date,Date Diff,Sales,Quantity,Discount,Profit
count,5968,5968,5968.000000,5968.000000,5968.000000,5968.000000,5968.000000
mean,2016-04-17 02:17:17.533512,2016-04-22 02:26:42.144772,3.593499,227.583067,3.819873,0.160023,27.494770
min,2014-01-03 00:00:00,2014-01-07 00:00:00,1.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2015-04-28 00:00:00,2015-05-04 00:00:00,3.000000,16.779000,2.000000,0.000000,1.467200
50%,2016-06-05 00:00:00,2016-06-09 00:00:00,4.000000,52.768000,3.000000,0.200000,8.301000
75%,2017-05-03 00:00:00,2017-05-07 06:00:00,4.000000,209.947500,5.000000,0.200000,28.765800
max,2017-12-30 00:00:00,2018-01-05 00:00:00,5.000000,22638.480000,14.000000,0.800000,8399.976000
std,NaN,NaN,1.061999,646.738998,2.246699,0.210782,250.010543

In [114]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 1 to 9994
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   str
 1   Order Date     9994 non-null   datetime64[us]
 2   Ship Date      9994 non-null   datetime64[us]
 3   Date Diff      9994 non-null   int64
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   str
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(2), str(14)
memory usage: 1.6 MB